name: CI, Sanity

on:
  push:
    branches-ignore:
      - master

jobs:
  needs-bump:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.2.0
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Latest version
      id: latestver
      uses: WyriHaximus/github-action-get-previous-tag@v1
    - uses: technote-space/get-diff-action@v4
      with:
        PATTERNS: |
          +(src|public)/**/*.*
        FILES: |
          yarn.lock
    - run: yarn check:bump ${{ steps.latestver.outputs.tag }}
      if: env.GIT_DIFF
